import Link from "next/link";

export const metadata = {
  title: "Terms & Conditions – Indian Pay Calculator | 7th & 8th CPC",
  description:
    "Read the Terms & Conditions for using the Indian Pay Calculator. Understand disclaimers, data accuracy, user responsibilities, and your rights when using our 7th & 8th Pay Commission Salary Calculators.",
  keywords: [
    "Indian Pay Calculator Terms",
    "Terms and Conditions",
    "CPC Salary Calculator Terms",
    "Disclaimer",
    "Privacy and Usage Policy",
    "7th Pay Commission",
    "8th Pay Commission",
  ],
  openGraph: {
    title: "Terms & Conditions – Indian Pay Calculator | 7th & 8th CPC",
    description:
      "Review the legal terms, disclaimers, and user responsibilities for using the Indian Pay Calculator tools, including DA, HRA, and Salary Calculators.",
    url: "https://www.indianpaycalculator.in/terms",
    siteName: "Indian Pay Calculator",
    type: "article",
  },
};

export default function Terms() {
  return (
    <div className="container mx-auto px-4 sm:px-6 lg:px-8 py-10 text-gray-800">
      {/* H1 */}
      <h1 className="text-3xl sm:text-4xl font-bold mb-6 text-center text-gray-900">
        Terms & Conditions
      </h1>

      <p className="text-gray-700 leading-relaxed text-base mb-6 text-center max-w-2xl mx-auto">
        Please read these Terms & Conditions carefully before using the{" "}
        <strong>Indian Pay Calculator</strong>. By accessing or using this website, you agree to be
        bound by these terms. If you do not agree with any part of these terms, please do not use the website.
      </p>

      {/* H2 - Section */}
      <h2 className="text-2xl font-semibold mt-8 mb-3 text-gray-900">
        1. General Information
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        The <strong>Indian Pay Calculator</strong> provides free online salary tools to help users calculate
        salary components under the <strong>7th and 8th Pay Commission</strong>. All calculations are
        based on publicly available government data and standard formulas for Dearness Allowance (DA),
        House Rent Allowance (HRA), Fitment Factor, and other pay elements.
      </p>

      {/* H2 - Accuracy */}
      <h2 className="text-2xl font-semibold mt-8 mb-3 text-gray-900">
        2. Accuracy of Information
      </h2>
      <h3 className="text-lg font-semibold mt-3 mb-2 text-gray-800">
        Disclaimer on Results
      </h3>
      <p className="text-gray-700 leading-relaxed mb-4">
        While we make every effort to ensure accuracy, the results generated by the calculator are
        for informational purposes only. Official salary figures may differ based on your department,
        grade pay level, allowances, and latest government orders. We recommend verifying results
        with your <strong>Pay & Accounts Office (PAO)</strong> or official government notifications.
      </p>

      {/* H2 - Limitation of Liability */}
      <h2 className="text-2xl font-semibold mt-8 mb-3 text-gray-900">
        3. Limitation of Liability
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        By using this website, you agree that the Indian Pay Calculator team is not responsible for
        any direct or indirect loss, financial discrepancy, or misunderstanding arising from the
        use of our tools or results. Users are solely responsible for the application and interpretation
        of the data provided here.
      </p>

      {/* H2 - Intellectual Property */}
      <h2 className="text-2xl font-semibold mt-8 mb-3 text-gray-900">
        4. Intellectual Property Rights
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        All website content, including text, graphics, logos, and design elements, are the property
        of <strong>Indian Pay Calculator</strong> and are protected by copyright laws. Unauthorized
        reproduction or redistribution of content is prohibited without prior written consent.
      </p>

      {/* H2 - External Links */}
      <h2 className="text-2xl font-semibold mt-8 mb-3 text-gray-900">
        5. External Links and Third-Party Services
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        Our website may include links to third-party websites for informational purposes.
        These sites are not under our control, and we are not responsible for their content,
        policies, or accuracy. We encourage users to read the privacy policies of any linked sites.
      </p>

      {/* H2 - Updates */}
      <h2 className="text-2xl font-semibold mt-8 mb-3 text-gray-900">
        6. Updates and Modifications
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        The Indian Pay Calculator reserves the right to modify or update these Terms & Conditions
        at any time without prior notice. Changes will be effective immediately upon being posted.
        Continued use of the site signifies acceptance of the updated terms.
      </p>

      {/* H2 - Contact */}
      <h2 className="text-2xl font-semibold mt-8 mb-3 text-gray-900">
        7. Contact and Feedback
      </h2>
      <p className="text-gray-700 leading-relaxed mb-4">
        For any questions, clarifications, or feedback related to our Terms & Conditions, please reach
        out via our{" "}
        <Link href="/contact" className="text-blue-600 hover:underline font-medium">
          Contact & Feedback
        </Link>{" "}
        page or email us at{" "}
        <span className="font-semibold">cpcforgovtemployees@gmail.com</span>.
      </p>

      <p className="text-gray-700 leading-relaxed mt-6 italic">
        Last Updated: {new Date().getFullYear()}
      </p>
    </div>
  );
}